#!/usr/bin/env bash
export dir="HELLWRLD"
export name="HELLWRLD"
export file="../src/LEX_lexem.c"
export src='#include "../src/inc.h"
int main(int argc, char **argv) {
    FILE *f;
    if((f = fopen(argv[argc-1], "r")) == NULL) return -1;
    TStructLex *ret = malloc(sizeof(TStructLex));
    ret->lex = NULL;
    ret->type = 0;
    LEX_getLexem(ret, f);
    while(ret->type != TYPE_EOF) {
        printf("%s\n", ret->lex);
        LEX_getLexem(ret, f);
    }
    free(ret);
    fclose(f);
    return 0;
}'
export input="begin



end."
export output="begin
end
.
"
export retCode=0
