#!/usr/bin/env bash
export dir="STRING"
export name="STRING"
export file="../src/LEX_lexem.c"
export src='#include "../src/inc.h"
int main(int argc, char **argv) {
    if (!argv[argc-1]) return 1;
    FILE *f = init(argv[argc-1]);
    TStructLex *ret = malloc(sizeof(TStructLex));
    if (!ret) return 1;
    ret->lex = NULL;
    ret->type = 0;
    while(LEX_getLexem(ret, f) != true) {
        printf("%s\n", ret->lex);
    }
    free(ret);
    fclose(f);
	return 0;
}'
export input="'What the heck'
'Is '#033' really ''!''?'
"
export output="What the heck
Is ! really '!'?
"
export retCode=0